Fixes Hyper-V should log a clear error message
When failing to access a remote SMB UNC path, Python raises
   WindowsError: [Error 123] The filename, directory name, or volume
label syntax is incorrect: '\\\\'
This issue happens during resize/cold migration.

This fix ensures that the Nova driver will report a clear error
message.

Change-Id: I735987f3c3f8c16759f6fbbb235a0156df832855
Closes-Bug: #1367786
(cherry pick from commit 42560abdf172bae2df5d3297003324f8c46b8037)